[phases.setup]
nixpkgs = ["...", "nodejs"]

[phases.install]
cmds = ["cd subscription-manager/backend && npm install"]

[phases.build]
cmds = ["cd subscription-manager/backend && npx prisma generate"]

[start]
cmd = "cd subscription-manager/backend && npm start"