[phases.setup]
nixPkgs = ["nodejs-18_x", "python3"]

[phases.install]
cmds = [
  "cd subscription-manager/backend",
  "npm install --production=false --ignore-scripts"
]

[phases.build]
cmds = [
  "cd subscription-manager/backend",
  "npx prisma generate"
]

[start]
cmd = "cd subscription-manager/backend && npm start"

[variables]
NODE_ENV = "production"